{{- $apiKeySecretName := include "zenoss.apiKeySecretName" . -}}
{{- $labels := include "prometheus-zenoss-adapter.labels" . -}}
{{- if and (.Values.zenoss.apiKey) (not .Values.zenoss.apiKeyExistingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $apiKeySecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ $labels | indent 4 }}
type: Opaque
data:
  api-key: {{ .Values.zenoss.apiKey | b64enc | quote }}
{{- end -}}

