apiVersion: v1
appVersion: "v1.2.0"
description: A Helm chart for zenoss-agent-kubernetes
name: zenoss-agent-kubernetes
version: "2.0.1"
icon: data:image/svg+xml;base64,PHN2ZyB2aWV3Qm94PSIwIDAgMzIgMzIiPgogICAgPHBhdGggZD0iTTIuODM0IDQuMzc3YTEwLjI0IDEwLjI0IDAgMCAxIDIuNDI4IDIuNDI4Yy4xNjQuMjMzLjMxMS40NjcKICAgICAgICAuNDUxLjcwOEExNS4yNTEgMTUuMjUxIDAgMCAxIDI3LjgzNiA4Ljc4QzI1LjIyOSAzLjIyNSAxNC4yOTYKICAgICAgICAtMy4wMDcyLjgzNCA0LjM3N3oiCiAgICAvPgogICAgPHBhdGggZD0iTTI4LjQ1IDE4LjY0QTEyLjI1NSAxMi4yNTUgMCAxIDEgMTYuMTk1IDYuMzkyYzYuNzY1IDAgMTIuMjUxCiAgICAgICAgNS40ODMgMTIuMjU1IDEyLjI0OHptLTEyLjI1NS02LjY5MmE2LjY5MiA2LjY5MiAwIDEgMCAwIDEzLjM4NAogICAgICAgIDYuNjkyIDYuNjkyIDAgMCAwIDAtMTMuMzg0eiIKICAgIC8+Cjwvc3ZnPgo=