{{- $apiKeySecretName := include "zenoss.apiKeySecretName" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zenoss-agent-kubernetes.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "zenoss-agent-kubernetes.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "zenoss-agent-kubernetes.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "zenoss-agent-kubernetes.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "zenoss-agent-kubernetes.fullname" . }}
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - /bin/zdm
          - run
          - --config-file=/etc/zdatamon/agent.yaml
          - --logconfig=/etc/zdatamon/logconfig.props
          - --logconfig-watch
          env:
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: K8S_POD
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: ZENOSS_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ $apiKeySecretName }}
                key: api-key
          {{- range $i, $endpoint := .Values.zenoss.endpoints }}
          - name: ZENOSS{{ add $i 1 }}_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ $apiKeySecretName }}-{{ $endpoint.name }}
                key: api-key
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: zdatamon-configs
            mountPath: /etc/zdatamon
          - name: zdatamon-ds-configs
            mountPath: /etc/zdatamon/configs
      volumes:
      - name: zdatamon-configs
        configMap:
          name: {{ include "zenoss-agent-kubernetes.fullname" . }}-configs
      - name: zdatamon-ds-configs
        configMap:
          name: {{ include "zenoss-agent-kubernetes.fullname" . }}-ds-configs
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end -}}
