{{- $apiKeySecretName := include "zenoss.apiKeySecretName" . -}}
{{- $labels := include "zenoss-agent-kubernetes.labels" . -}}
{{- if and (.Values.zenoss.apiKey) (not .Values.zenoss.apiKeyExistingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $apiKeySecretName }}
  namespace: kube-system
  labels:
{{ $labels | indent 4 }}
type: Opaque
data:
  api-key: {{ .Values.zenoss.apiKey | b64enc | quote }}
{{- end -}}
{{- range $i, $endpoint := .Values.zenoss.endpoints -}}
{{- if not $endpoint.apiKeyExistingSecret -}}
{{- if ne $i 0 -}}{{printf "\n---\n" }}{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $apiKeySecretName }}-{{ $endpoint.name }}
  namespace: kube-system
  labels:
{{ $labels | indent 4 }}
type: Opaque
data:
  api-key: {{ required "zenoss.endpoints[].apiKey must be set" $endpoint.apiKey | b64enc | quote }}
{{- end }}
{{- end -}}